name: State Manager Unit Tests

on:
  push:
    branches: [main]
    paths:
      - 'state-manager/**'
  pull_request:
    branches: [main]
    paths:
      - 'state-manager/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dev dependencies with uv
        working-directory: state-manager
        run: |
          uv sync --group dev
          
      - name: Run full test suite with coverage
        working-directory: state-manager
        env:
          MONGO_URI: mongodb://admin:password@localhost:27017
          MONGO_DATABASE_NAME: test_exosphere_state_manager
          STATE_MANAGER_SECRET: test-secret-key
          SECRETS_ENCRYPTION_KEY: YTzpUlBGLSwm-3yKJRJTZnb0_aQuQQHyz64s8qAERVU=
        run: |
          uv run pytest tests/ --cov=app --cov-report=xml --cov-report=term-missing --cov-report=html -v --junitxml=full-pytest-report.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: exospherehost/exospherehost
          files: state-manager/coverage.xml
          flags: unit-tests
          name: state-manager-coverage-report
          fail_ci_if_error: true